/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      },
      colors: {
        surface: {
          DEFAULT: "var(--md-sys-color-surface)",
          dim: "var(--md-sys-color-surface-dim)",
          bright: "var(--md-sys-color-surface-bright)",
          "container-lowest": "var(--md-sys-color-surface-container-lowest)",
          "container-low": "var(--md-sys-color-surface-container-low)",
          container: "var(--md-sys-color-surface-container)",
          "container-high": "var(--md-sys-color-surface-container-high)",
          "container-highest": "var(--md-sys-color-surface-container-highest)",
          variant: "var(--md-sys-color-surface-variant)",
          tint: "var(--md-sys-color-surface-tint)",
        },
        "on-surface": {
          DEFAULT: "var(--md-sys-color-on-surface)",
          variant: "var(--md-sys-color-on-surface-variant)",
        },
        background: {
          DEFAULT: "var(--md-sys-color-background)",
        },
        "on-background": "var(--md-sys-color-on-background)",
        outline: {
          DEFAULT: "var(--md-sys-color-outline)",
          variant: "var(--md-sys-color-outline-variant)",
        },
        primary: {
          DEFAULT: "var(--md-sys-color-primary)",
          on: "var(--md-sys-color-on-primary)",
          container: "var(--md-sys-color-primary-container)",
          "on-container": "var(--md-sys-color-on-primary-container)",
          fixed: "var(--md-sys-color-primary-fixed)",
          "fixed-dim": "var(--md-sys-color-primary-fixed-dim)",
          "on-fixed": "var(--md-sys-color-on-primary-fixed)",
          "on-fixed-variant": "var(--md-sys-color-on-primary-fixed-variant)",
        },
        "inverse-primary": "var(--md-sys-color-inverse-primary)",
        secondary: {
          DEFAULT: "var(--md-sys-color-secondary)",
          on: "var(--md-sys-color-on-secondary)",
          container: "var(--md-sys-color-secondary-container)",
          "on-container": "var(--md-sys-color-on-secondary-container)",
        },
        tertiary: {
          DEFAULT: "var(--md-sys-color-tertiary)",
          on: "var(--md-sys-color-on-tertiary)",
          container: "var(--md-sys-color-tertiary-container)",
          "on-container": "var(--md-sys-color-on-tertiary-container)",
        },
        error: {
          DEFAULT: "var(--md-sys-color-error)",
          on: "var(--md-sys-color-on-error)",
          container: "var(--md-sys-color-error-container)",
          "on-container": "var(--md-sys-color-on-error-container)",
        },
        warning: {
          DEFAULT: "var(--md-sys-color-warning)",
          on: "var(--md-sys-color-on-warning)",
          container: "var(--md-sys-color-warning-container)",
          "on-container": "var(--md-sys-color-on-warning-container)",
        },
        success: {
          DEFAULT: "var(--md-sys-color-success)",
          on: "var(--md-sys-color-on-success)",
          container: "var(--md-sys-color-success-container)",
          "on-container": "var(--md-sys-color-on-success-container)",
        },
        inverse: {
          surface: "var(--md-sys-color-inverse-surface)",
          "on-surface": "var(--md-sys-color-inverse-on-surface)",
        },
        scrim: "var(--md-sys-color-scrim)",
        primaryColor: "var(--md-sys-color-primary)",
        secondaryColor: "var(--md-sys-color-secondary)",
      },
      borderRadius: {
        none: "var(--md-sys-shape-corner-none)",
        "extra-sm": "var(--md-sys-shape-corner-extra-small)",
        sm: "var(--md-sys-shape-corner-small)",
        DEFAULT: "var(--md-sys-shape-corner-medium)",
        md: "var(--md-sys-shape-corner-medium)",
        lg: "var(--md-sys-shape-corner-large)",
        xl: "var(--md-sys-shape-corner-extra-large)",
        full: "var(--md-sys-shape-corner-full)",
        "extra-sm-top": "var(--md-sys-shape-corner-extra-small-top)",
        "lg-top": "var(--md-sys-shape-corner-large-top)",
        "xl-top": "var(--md-sys-shape-corner-extra-large-top)",
      },
      boxShadow: {
        level0: "var(--md-sys-elevation-level0)",
        level1: "var(--md-sys-elevation-level1)",
        level2: "var(--md-sys-elevation-level2)",
        level3: "var(--md-sys-elevation-level3)",
        level4: "var(--md-sys-elevation-level4)",
        level5: "var(--md-sys-elevation-level5)",
      },
      transitionDuration: {
        short1: "50ms",
        short2: "100ms",
        short3: "150ms",
        short4: "200ms",
        medium1: "250ms",
        medium2: "300ms",
        medium3: "350ms",
        medium4: "400ms",
        long1: "450ms",
        long2: "500ms",
        long3: "550ms",
        long4: "600ms",
      },
      transitionTimingFunction: {
        emphasized: "cubic-bezier(0.05, 0.7, 0.1, 1.0)",
        "emphasized-accelerate": "cubic-bezier(0.3, 0.0, 0.8, 0.15)",
        standard: "cubic-bezier(0.2, 0.0, 0.0, 1.0)",
        legacy: "cubic-bezier(0.4, 0.0, 0.6, 1.0)",
      },
      fontSize: {
        "display-large": ["3.5625rem", { lineHeight: "4rem", fontWeight: "400" }],
        "display-medium": ["2.8125rem", { lineHeight: "3.25rem", fontWeight: "400" }],
        "display-small": ["2.25rem", { lineHeight: "2.75rem", fontWeight: "400" }],
        "headline-large": ["2rem", { lineHeight: "2.5rem", fontWeight: "400" }],
        "headline-medium": ["1.75rem", { lineHeight: "2.25rem", fontWeight: "400" }],
        "headline-small": ["1.5rem", { lineHeight: "2rem", fontWeight: "400" }],
        "title-large": ["1.375rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "title-medium": ["1rem", { lineHeight: "1.5rem", fontWeight: "500" }],
        "title-small": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
        "label-large": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
        "label-medium": ["0.75rem", { lineHeight: "1rem", fontWeight: "600" }],
        "label-small": ["0.6875rem", { lineHeight: "1rem", fontWeight: "600" }],
        "body-large": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-medium": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "body-small": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideInLeft: {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        scaleIn: {
          from: { opacity: "0", transform: "scale(0.92)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        pulse: {
          "0%, 100%": { opacity: "0.6" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        fadeIn: "fadeIn 200ms cubic-bezier(0.2, 0.0, 0.0, 1.0) forwards",
        slideUp: "slideUp 350ms cubic-bezier(0.05, 0.7, 0.1, 1.0) forwards",
        slideInLeft: "slideInLeft 300ms cubic-bezier(0.05, 0.7, 0.1, 1.0) forwards",
        scaleIn: "scaleIn 250ms cubic-bezier(0.05, 0.7, 0.1, 1.0) forwards",
        shimmer: "shimmer 1.5s linear infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
